import Head from "next/head";
import { getAllPostsMetadata } from "@/lib/get-posts-data";
import Header from "@/components/Header";
import Link from "next/link";

export default function Home({ postsMetaData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Header /> */}
        <div className="info-container">
          {postsMetaData?.map((data) => {
            return (
              <div key={data.metadata.id}>
                <Link
                  className="post-title"
                  href={`/blog/${data.metadata.id}`}
                  key={data.metadata.title}
                >
                  {data.metadata.title}
                </Link>
                <h2 className="post-title">{data.metadata.title}</h2>
                <p className="post-description">{data.metadata.description}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const postsMetaData = getAllPostsMetadata();
  return {
    props: {
      postsMetaData,
    },
  };
}
